<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<IsPackable>false</IsPackable>
		<RootNamespace>FluentGwt.Tests</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="AwesomeAssertions" Version="9.6.0" />
		<PackageReference Include="xunit.v3" Version="4.0.1" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\src\FluentGwt\FluentGwt.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Compile Update="GivenTests.*.cs">
			<DependentUpon>GivenTests.cs</DependentUpon>
		</Compile>
		<Compile Update="ChainTests.*.cs">
			<DependentUpon>ChainTests.cs</DependentUpon>
		</Compile>
	</ItemGroup>

</Project>
