<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<AssemblyName>FluentGwt</AssemblyName>
		<RootNamespace>FluentGwt</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="AwesomeAssertions" Version="9.6.0" />
		<PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.12" />
		<PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="10.0.12" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.12" />
		<PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="10.0.12" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.12" />
		<PackageReference Include="Microsoft.Extensions.Diagnostics.Testing" Version="10.10.0" />
		<PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.12" />
		<PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.12" />
		<PackageReference Include="Microsoft.Extensions.TimeProvider.Testing" Version="10.10.0" />
	</ItemGroup>
	
	<ItemGroup>
		<Compile Update="Given.Base.cs">
			<DependentUpon>Given.cs</DependentUpon>
		</Compile>
		<Compile Update="Given.TargetedExtensions.cs">
			<DependentUpon>Given.cs</DependentUpon>
		</Compile>
		<Compile Update="Given.Targeted.cs">
			<DependentUpon>Given.cs</DependentUpon>
		</Compile>
		<Compile Update="Given.UntargetedExtensions.cs">
			<DependentUpon>Given.cs</DependentUpon>
		</Compile>
		<Compile Update="Given.Untargeted.cs">
			<DependentUpon>Given.cs</DependentUpon>
		</Compile>
		<Compile Update="StateHolder.Extensions.cs">
			<DependentUpon>StateHolder.cs</DependentUpon>
		</Compile>
	</ItemGroup>

</Project>
